### ISSUE TITLE
nginx before docker registry ui

### ISSUE THREAD

**Issue by bchanan03** [mkuchin/docker-registry-web#16]
Hi,
I tried placing nginx proxy pass to to the docker registry ui adding a new sub-folder 'registry'
the page is loaded but the resources .css .js failed to load.

Here is the nginx configuration:
location ~ ^/registry/.*$ {
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $remote_addr;
proxy_set_header Host $host;
proxy_set_header Connection "Keep-Alive";
proxy_set_header Proxy-Connection "Keep-Alive";
proxy_http_version 1.1;
proxy_pass http://secure-registry-web.saas.lab:8080;
rewrite ^/registry/(.*) /$1 break;
}

**Comment by bchanan03** [comment]
when trying curl http://myweb.com/registry/
it should have proxy pass to container running the docker registry web
but it failed to load .css .js files

**Comment by s19n** [comment]
+1

**Comment by joshrivers** [comment]
This worked for me:

    location /registry {
        rewrite /registry/(.*) /$1  break;
        rewrite /registry /  break;
        proxy_pass                          http://registry-web;
    }
    location /assets {
        proxy_pass                          http://registry-web;
    }

I would like it if the assets directory was added as a relative path. It looks like grails is opinionated about turning relative paths into absolute paths when using the asset pipeline. There is probably a way to override this, or to pass in a base path using an environment variable, but I couldn't find it in my first 30 minutes of looking.

**Comment by mkuchin** [comment]
I'd added environment variable `CONTEXT_PATH` to access registry-web with prefix.
Simply run registry-web with `-e CONTEXT_PATH=/app` and registry will be available on url http://hostname/app/

**Comment by joshrivers** [comment]
Just tested the new image from docker hub. Works perfectly with nginx.conf

    location /registry {
        proxy_pass                          http://registry-web;
    }

and docker run with:

    -e CONTEXT_PATH=/registry

Thank you!!

**Comment by mkuchin** [comment]
Great!
