### ISSUE TITLE
Not actually deleted images

### ISSUE THREAD

**Issue by Bennow** [mkuchin/docker-registry-web#25]
**Hi. Great project! Thanx!**

_So, the bug is about deleting :)_

Some image can be deleted, but some not. Here is the log:

`registryui_1 | 2016-03-29 10:24:44,494 [http-bio-8080-exec-6] INFO  web.RepositoryController  - Manifest digest: sha256:b7af264c107b0571aa69b13b07f4063c9e516995042fa013b7bb2117464fa157
registryui_1 | 2016-03-29 10:24:44,494 [http-bio-8080-exec-6] INFO  web.RepositoryController  - Deleting manifest
registryui_1 | 2016-03-29 10:24:44,500 [http-bio-8080-exec-6] INFO  web.RestService  - 202
registryui_1 | 2016-03-29 10:25:13,167 [http-bio-8080-exec-3] INFO  web.RepositoryController  - Manifest digest: sha256:60c1ea184aff995c2edfaeb347c92c41e44c137724753b49f29296877d290f85
registryui_1 | 2016-03-29 10:25:13,167 [http-bio-8080-exec-3] INFO  web.RepositoryController  - Deleting manifest
registryui_1 | 2016-03-29 10:25:13,174 [http-bio-8080-exec-3] INFO  web.RestService  - 404`

As you see, the first is ok = 202
The second not found = 404

But even 202 response code - the data actually not deleted.
In blob dir layers remained.

PS. The blob "60c1ea184aff995c2edfaeb347c92c41e44c137724753b49f29296877d290f85" doesn't exist on filesystem.
So, may be it is wrong identity for image or something like that.

**Comment by mkuchin** [comment]
@Bennow, thanks for bug report. Images pushed from docker 1.10 generating  new version of manifest. It should be fixed now. 

However all deletes are soft deletes of manifest only. Deleting of blobs is dangerous as other images may become broken if they rely on same blob. Upcoming release of [docker registry 2.4.0](https://github.com/docker/distribution/releases/tag/v2.4.0-rc.0) will introduce garbage collection of unused blobs.

**Comment by Bennow** [comment]
Ok, clear!
btw, i use this tool to delete blobs:
https://github.com/burnettk/delete-docker-registry-image
May be it would be useful for you.
