### ISSUE TITLE
Delete don't work

### ISSUE THREAD

**Issue by Rohlik** [mkuchin/docker-registry-web#28]
Hi,
thx for this project!
When I deleted image via your web UI and then use `curl https://registry:5000/v2/_catalog` I can still see my deleted image in curl response.
Is it problem with your web ui or with registry?
Using hyper/docker-registry-web:latest

**Comment by mkuchin** [comment]
It's registry behaviour. 
If you check response from `/v2/${name}/tags/list` it should show you empty list.
Web UI doesn't show any repositories from `/v2/_catalog` response with 0 tags.

**Comment by Rohlik** [comment]
I see something like this in response `{"name":"busybox","tags":null}`, so image don't exist in repository, right?

**Comment by mkuchin** [comment]
correct

**Comment by Rohlik** [comment]
Ok, closing this ticket. Thx for help!
