### ISSUE TITLE
Image size appears incorrectly

### ISSUE THREAD

**Issue by liyaka** [mkuchin/docker-registry-web#34]
Image size bigger than 2GB appears as 2GB

**Comment by mkuchin** [comment]
@liyaka can you confirm if problem fixed in latest version?

**Comment by liyaka** [comment]
not fixed - still appears 2GB...

**Comment by mkuchin** [comment]
Can you show me exact image size? It appears in `data-sort` attribute of `td` of corresponding cell.
Something like this:
`<td data-sort="346008785">329 MB</td>`

**Comment by mkuchin** [comment]
It may be due to rounding down to the nearest GB boundary, so every size less than 3GB was rounded to 2 GB. It's changed in latest version so one digit shown after decimal point for sizes large than 1MB.

**Comment by liyaka** [comment]
Here is one example:
<tr>
  <td>9680312575c</td>
  <td><a href="/tag/thetaray%252Ftr-worker/1.13.0.42">1.13.0.42</a></td>
  <td data-sort="2016-04-04T13:04:52"><abbr title="2016-04-04T13:04:52">2 weeks ago</abbr></td>
  <td>23</td>
  <td data-sort="2765442066">2 GB</td>
  <td><a href="/delete/1.13.0.42/thetaray%252Ftr-worker">Delete</a></td>
</tr>

the same image:
xxxx:5000/thetaray/tr-worker         1.13.0.42              ec22d5aa7c7d        13 days ago         4.757 GB

**Comment by mkuchin** [comment]
Thanks for info. 
Are you comparing size in registry and output from command `docker images` ?
Size reported in `docker images`  typically larger than registry size because registry store compressed layers. 
For example docker hub shows 347 MB for `docker-registry-web:latest` but `docker images` shows 554 MB.

**Comment by liyaka** [comment]
Can you please set the size in more precise format, like 2.765 GB in this example? Thanks!

**Comment by mkuchin** [comment]
In latest version it will show 2.8 GB for your example.

**Comment by liyaka** [comment]
Thanks!
