### ISSUE TITLE
Max repos list limited to 100 on index

### ISSUE THREAD

**Issue by santiagax99** [mkuchin/docker-registry-web#36]
As i can see in RepositoryController.groovy restService.get('_catalog') is used to fill-up repos list, but by default /v2/_catalog from registry returns only 100 records. If there is more than 100 repos in registry we will see only first 100. 

Is it possible to add variable or something else to have ability to fetch full list ? 
From apiit can be done by passing ?n=<SIZE> to request, like http://localhost/v2/_catalog?n=1000

**Comment by mkuchin** [comment]
Thanks for report, it seems it is better to check Link header and implement pagination:

> For registries with a large number of repositories, this response may be quite large. If such a response is expected, one should use pagination. A registry may also limit the amount of responses returned even if pagination was not explicitly requested. In this case the Link header will be returned along with the results, and subsequent results can be obtained by following the link as if pagination had been initially requested. 
> 
> For details of the Link header, please see the [Pagination](https://docs.docker.com/registry/spec/api/#pagination) section.

**Comment by mkuchin** [comment]
Pagination had been implemented in latest version on docker hub.

**Comment by santiagax99** [comment]
Looks good! Thanks.
