### ISSUE TITLE
REGISTRY AUTH setting

### ISSUE THREAD

**Issue by bergtwvd** [mkuchin/docker-registry-web#39]
I currently need to hardwire authentication data with the container. Would it be possible to provide a popup window to request for username and password in case of basic authentication... ?

**Comment by mkuchin** [comment]
I'm working on token authentication implementation. It will use same credentials across registry and web ui. It will be available later this month.

**Comment by bergtwvd** [comment]
Sounds great. All I want to do is to host the Registry UI on the same host as the Registry, and provide bott services on the internet, requiring users the authenticate themselves via the UI (otherwise the whole setup (https + basic auth) does not make sense).

**Comment by mkuchin** [comment]
@bergtwvd, new version with full authentication support has been released.
Please have a look at [config examples](https://github.com/mkuchin/docker-registry-web/tree/master/examples).
