### ISSUE TITLE
Fail to login repository

### ISSUE THREAD

**Issue by bergtwvd** [mkuchin/docker-registry-web#48]
* I have set up the nginx configuration, with SSL enabled on host app-docker02.xxxx. I generated the keys following the instructions at https://www.digitalocean.com/community/tutorials/how-to-set-up-a-private-docker-registry-on-ubuntu-14-04.

* I also set DOCKER_OPTS="--insecure-registry=app-docker02.xxxx:443 -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock" for app-docker02 and app-docker03.

* I create a user with write-all access via the registry webui, from a browser on another machine.

* From app-docker02 I do: docker login app-docker02.xxxx:443. After providing username/password I successfuly am logged in and can push images. From the browser I see them listed.

* From app-docker03 I do: docker login app-docker02.xxxx:443. After providing username/password I get the following message:
```
...
Username: bergtwvd
Password:
Error response from daemon: Get https://app-docker02.xxxx:443/v2/: Get http://localhost:8080/api/auth?account=bergtwvd&client_id=docker&offline_token=true&service=localhost: dial tcp 127.0.0.1:8080: getsockopt: connection refused
```

Output on console is
```
registry_1      | time="2016-06-30T23:30:19.629837536Z" level=debug msg="authorizing request" go.version=go1.6.2 http.request.host="app-docker02.xxxx:443" http.request.id=57793cb2-29ea-4c7f-adec-d3fc985e333b http.request.method=GET http.request.remoteaddr=xx.xx.xx.xx http.request.uri="/v2/" http.request.useragent="docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.13.0-76-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))" instance.id=2710c31d-0002-4d9b-998a-2b370137a754 version=v2.4.1
nginx_1         | xx.xx.xx.xx - - [30/Jun/2016:23:30:19 +0000] "GET /v2/ HTTP/1.1" 401 87 "-" "docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.13.0-76-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \x5C(linux\x5C))" "-"
registry_1      | time="2016-06-30T23:30:19.630135837Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.6.2 http.request.host="app-docker02.xxxx:443" http.request.id=57793cb2-29ea-4c7f-adec-d3fc985e333b http.request.method=GET http.request.remoteaddr=xx.xx.xx.xx http.request.uri="/v2/" http.request.useragent="docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.13.0-76-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))" instance.id=2710c31d-0002-4d9b-998a-2b370137a754 version=v2.4.1
registry_1      | 172.18.0.4 - - [30/Jun/2016:23:30:19 +0000] "GET /v2/ HTTP/1.0" 401 87 "" "docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.13.0-76-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))"
```
Any ideas what is going wrong?

**Comment by mkuchin** [comment]
Yes, docker engine trying to obtain auth token on URL `http://localhost:8080/api/auth`.
It's `auth.token.realm` config option of docker registry. Please put external hostname of your web UI instead of `localhost` in this config property.

**Comment by bergtwvd** [comment]
Thanks, worked!
