### ISSUE TITLE
username supported in imagename?

### ISSUE THREAD

**Issue by bergtwvd** [mkuchin/docker-registry-web#49]
I have a user "test" defined via the web UI (with rw access), but this does not work:

```
docker@docker-1:~$ docker push localhost/test/hello-world:latest
The push refers to a repository [localhost/test/hello-world]
beae8ae41561: Preparing
unauthorized: authentication required
```

**Comment by mkuchin** [comment]
Good find, @bergtwvd. Image name glob `*` in default **write-all** role allows only image names without `/`. Glob `**` will alow any name. To allow any name please add following ACL to **write-all** role: 
        
    IP: '*', Repository: '**', Permissions: 'pull, push'

**Comment by bergtwvd** [comment]
Thanks, works.

I also wonder how to define a role with no image deletion privilege. Seems not possible.

**Comment by mkuchin** [comment]
Currently, there is no separate role to allow deletion privilege in UI, only system-wide configuration key to enable read-only mode (`registry.readonly=true`). 
I'm planning to add `UI_DELETE` special role in next release.

**Comment by bergtwvd** [comment]
Another option to consider is to restrict deletion to images where the username is equal to the registry  login name.

**Comment by mkuchin** [comment]
Good point. I didn't realise that delete permission may be required per repository basis.
Going to integrate *ui-delete* permission into ACLs, so you would need to add following ACL to user role to allow deletes from UI:
    
    IP: 'local', Repository: 'repo-name', Permissions: 'ui-delete' 

How does that sound to you?

**Comment by mkuchin** [comment]
I made **UI_DELETE** role which will have ACL: 
    
    IP: 'local', Repository: '**', Permissions: 'ui-delete' 

It will allow delete in UI for any repository. You can modify it as you like or create other roles restricted by repository name. This role will be automatically created on new user database creation.

It is available in new release 0.1.2

**Comment by bergtwvd** [comment]
Again, thanks! 
For my understanding, if I have three users A, B, and C, then I need to define/assign three roles RA, RB and RC that restricts each user to deleting only his own repository?

**Comment by mkuchin** [comment]
Yes, it currently implemented that way. 
I'm planning to add the support of `${username}` placeholder in name glob so you can make a single role for such cases.
