### ISSUE TITLE
ask for help how to login a registry from a remote host

### ISSUE THREAD

**Issue by TUTUBIG** [mkuchin/docker-registry-web#58]
hi, i have installed the registry:2 and registry-web ,and all goes correct in the  localhost.but when i login from other host ,it seems to be wrong   
## it goes wrong:

> **sudo docker login dockerkincity.com:5000**
>   `Error response from daemon: Get https://dockerkincity.com:5000/v2/users/: tls: oversized record received with length 20527`

**i have set the CN 
 i have set the hosts and the ping to dockerkincity.com is correc
 i have put the cert file to the host which runs registry:2 and registry-web [conf/auth.key] to the remote host which is going to login in the registry:2 [/etc/docker/certs.d/dockerkincity.com:5000/ca.crt ]** 

```
openssl req -new -newkey rsa:4096 -days 365 -subj "/CN=dockerkincity.com" \
        -nodes -x509 -keyout conf/auth.key -out conf/auth.cert   
```

what's wrong ? what i have forgotten?

Thanks!

**Comment by TUTUBIG** [comment]
can you write a document to describe how to set up a remote host to login in the registry

**Comment by mkuchin** [comment]
It seems to me that docker registry listening on port 5000 for HTTP connections, but docker using HTTPS instead unless you specify `DOCKER_OPTS="--insecure-registry myregistrydomain.com:5000"` in docker config. 
Most close to production config examples are here: https://github.com/mkuchin/docker-registry-web/tree/master/examples/nginx-auth-enabled
I'm going to write guide on how to setup secure docker registry with letsencrypt next week.

**Comment by TUTUBIG** [comment]
thanks for your help!
did you mean my docker registry hasn't open TLS?and can i use Https while using the registry-web

**Comment by aessig** [comment]
@mkuchin Did you have a chance to write a guide on how to setup secure docker registry with letsencrypt ? I would really appreciate it as I'm struggling to set that up. Thanks
