### ISSUE TITLE
delete not working

### ISSUE THREAD

**Issue by vbichov** [mkuchin/docker-registry-web#8]
when pressing "Delete" , getting:

`2015-09-08 11:11:05,520 [http-bio-8080-exec-10] INFO  web.RepositoryController  - null
2015-09-08 11:11:05,520 [http-bio-8080-exec-10] INFO  web.RepositoryController  - Deleting manifest
2015-09-08 11:11:05,523 [http-bio-8080-exec-10] INFO  web.RestService  - 404
`

**Comment by mkuchin** [comment]
Could you provide registry logs  also?

**Comment by vbichov** [comment]
This is an example for a couple of test images:

172.17.0.1 - - [16/Sep/2015:07:18:41 +0000] "GET /v2/gliderlabs%252Fconsul/manifests/test HTTP/1.1" 404 19 "" "Java/1.7.0_79"
172.17.0.1 - - [16/Sep/2015:07:18:41 +0000] "DELETE /v2/gliderlabs%252Fconsul/manifests/null HTTP/1.1" 404 19 "" "Java/1.7.0_79"
172.17.0.1 - - [16/Sep/2015:07:18:41 +0000] "GET /v2/gliderlabs/consul/tags/list HTTP/1.1" 200 45 "" "Java/1.7.0_79"
172.17.0.1 - - [16/Sep/2015:07:18:41 +0000] "GET /v2/gliderlabs/consul/manifests/test HTTP/1.1" 200 14552 "" "Java/1.7.0_79"


172.17.0.1 - - [16/Sep/2015:07:20:28 +0000] "GET /v2/master%252Fkibana/manifests/prod HTTP/1.1" 404 19 "" "Java/1.7.0_79"
172.17.0.1 - - [16/Sep/2015:07:20:28 +0000] "DELETE /v2/master%252Fkibana/manifests/null HTTP/1.1" 404 19 "" "Java/1.7.0_79"

**Comment by mkuchin** [comment]
Right. Is your repository names contains /  like 'gliderlabs/consul'?

**Comment by mkuchin** [comment]
Please try to pull latest image version, it should be fixed.

**Comment by vbichov** [comment]
The tag is removed, however, once the "delete" button is pressed the browser (Firefox) returns a blank empty page, rather then returning the repositories page.
Still, functionally, it works... Thank you!
